# Generated by Django 4.2.7 on 2025-08-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(default='Hostify Hostel', max_length=200)),
                ('hostel_address', models.TextField(default='Hostel Address')),
                ('contact_number', models.CharField(default='+92-300-0000000', max_length=20)),
                ('email', models.EmailField(default='admin@hostify.com', max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
