# Generated by Django 4.2.7 on 2025-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='evening_shift',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday'), ('Leave', 'Leave'), ('Null', 'Null')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='morning_shift',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday'), ('Leave', 'Leave'), ('Null', 'Null')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='night_shift',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday'), ('Leave', 'Leave'), ('Null', 'Null')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='summary',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday'), ('Leave', 'Leave'), ('Null', 'Null')], default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_type',
            field=models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('night_shift', 'Night Shift')], max_length=20),
        ),
    ]
